name: Publish

on:
  workflow_dispatch:

env:
  RELEASE_PATH: release
  PUBLISHER_NAME: xfy9326

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      
      - name: Read version
        run: |
          cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]' > VSCODE_RELEASE_VERSION
          [ -s VSCODE_RELEASE_VERSION ] && echo "VSCODE_RELEASE_VERSION=$(cat VSCODE_RELEASE_VERSION)" >> $GITHUB_ENV
          echo "Release version: $(cat VSCODE_RELEASE_VERSION)"
      
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1

      - name: Setup VSCode develop environment
        run: |
          npm install -g vsce
      
      - name: Package
        run: |
          cd $GITHUB_WORKSPACE
          mkdir $RELEASE_PATH
          vsce package -o $RELEASE_PATH/
      
      - name: Publish
        env:
          VSCE_PAT: ${{ secrets.VS_MARKET_PAT }}
        run: |
          vsce publish

      - name: Github release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: v${{ env.VSCODE_RELEASE_VERSION }}
          tag_name: ${{ env.VSCODE_RELEASE_VERSION }}
          files: release/*
          body: Github Action release
        
